import React, { useEffect, useState } from 'react';
import { generateComparisonAnalysis } from '../services/gemini';
import { AnalysisResponse } from '../types';

const Analysis: React.FC = () => {
  const [data, setData] = useState<AnalysisResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    const fetchAnalysis = async () => {
      const result = await generateComparisonAnalysis();
      if (mounted && result) {
        setData(result);
        setLoading(false);
      }
    };
    fetchAnalysis();
    return () => { mounted = false; };
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[400px] space-y-6">
        <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
        <p className="text-slate-400 text-lg animate-pulse">Searching the web for the absolute latest benchmarks...</p>
        <div className="flex gap-2 text-xs text-slate-600 font-mono">
           <span>Querying: DeepSeek R1</span>
           <span>•</span>
           <span>Claude 3.7</span>
           <span>•</span>
           <span>Qwen 2.5 Max</span>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="text-center text-red-400 p-10 bg-slate-800/50 rounded-xl border border-red-900/50">
        Failed to load analysis. Please check your connection or API Key.
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="bg-gradient-to-br from-blue-900/50 via-slate-900 to-slate-900 p-8 rounded-2xl border border-blue-500/30 shadow-2xl">
        <h2 className="text-2xl font-bold text-white mb-2">Live Market Analysis</h2>
        <p className="text-blue-200">
           AI-generated report based on real-time search results.
        </p>
      </div>

      {/* Main Content (Markdown-ish rendering) */}
      <div className="bg-slate-800 p-8 rounded-2xl border border-slate-700 shadow-lg">
        <div className="prose prose-invert max-w-none text-slate-300 whitespace-pre-wrap leading-relaxed">
          {data.markdown}
        </div>
      </div>

      {/* Citations / Grounding */}
      {data.groundingChunks && data.groundingChunks.length > 0 && (
        <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-800">
          <h3 className="text-sm uppercase tracking-wider text-slate-500 font-bold mb-4 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
            Sources & Citations
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {data.groundingChunks.map((chunk, idx) => (
              chunk.web?.uri ? (
                <a 
                  key={idx}
                  href={chunk.web.uri}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center p-3 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-blue-500 transition-all group"
                >
                  <span className="bg-slate-900 text-slate-400 text-xs font-bold px-2 py-1 rounded mr-3 group-hover:text-blue-400">
                    {idx + 1}
                  </span>
                  <span className="text-sm text-slate-300 truncate group-hover:text-white">
                    {chunk.web.title || chunk.web.uri}
                  </span>
                </a>
              ) : null
            ))}
          </div>
        </div>
      )}
      
      <div className="flex justify-center">
        <p className="text-xs text-slate-600 italic">
           Analysis generated by Gemini 3 Pro using Google Search Grounding.
        </p>
      </div>
    </div>
  );
};

export default Analysis;
